In [16]:
import numpy as np
def kabsch(qrHidden, qrOdom):

    # First 2 QR in hidden frame
    Q = np.empty((2,3))
    Q[0,0] = qrHidden[0][0]
    Q[0,1] = qrHidden[0][1]
    Q[1,0] = qrHidden[1][0]
    Q[1,1] = qrHidden[1][1]
    Q[0,2] = 0
    Q[1,2] = 0
    # First 2 QR in odom frame
    P = np.empty((2,3))
    P[0,0] = qrOdom[0][0] #.position.x
    P[0,1] = qrOdom[0][1] #.position.y
    P[1,0] = qrOdom[1][0] #.position.x
    P[1,1] = qrOdom[1][1] #.position.y
    P[0,2] = 0
    P[1,2] = 0
    # print("Q\n",Q)
    # print("P\n",P)


    # Find centroids and subtract mean
    centQ = np.mean(Q,axis=0)
    centP = np.mean(P,axis=0)
    Q = np.subtract(Q,centQ)
    P = np.subtract(P,centP)


    # Compute covariance matrix
    H = Q.T @ P

    # Singular Value Decomposition
    U,S,Vt = np.linalg.svd(H)
    V = Vt.T

    # Decide whether we need to correct our rotation matrix to ensure a right-handed coordinate system
    d = np.sign(np.linalg.det(V @ U.T))
    D = np.diag((1,1,d))

    # Rotation Matrix
    R = V @ (D @ U.T)
    # R = Vt @ U.T

    t = - (R @ centQ) + centP

    # print("t \n",t)
    # print("R \n",R)

    return t,R

def transformNextQr(t,R,q):
    Q = np.empty((1,3))
    Q[0,0] = q[0]
    Q[0,1] = q[1]
    Q[0,2] = 0

    Q = Q.reshape((3,1))
    t = t.reshape((3,1))

    # print((R @ Q)+t)
    return (R @ Q) + t



In [18]:
### DEFINITION LAYOUT 1 ###

qrCurrHidden = [(3.03,1.15),(2.67,3.23),(0.1,3.5),(-3.08,1.95),(-3.08,0.0)]
qrNextHidden = [(2.7,3.27),(0.1,3.5),(-3.1,2.0),(-3.1,0.0),(3.0,1.2)]


qrOdom = [(-4.226,3.176),(-6.003,3.2173),(-6.708,0.990),(-5.106,-3.344),(-3.670,-3.178)]
print("QR pose in odom:\n",qrOdom)

print("\nFrom qr 4 and 5, detect odom position of 1: ")
print("\n4 in hidden frame: {}".format(qrCurrHidden[3]))
print("4 in Odom: {}".format(qrOdom[3]))
print("\n5 in hidden frame: {}".format(qrCurrHidden[4]))
print("5 in Odom: {}".format(qrOdom[4]))

t,R = kabsch( [qrCurrHidden[3],qrCurrHidden[4]], [qrOdom[3],qrOdom[4]])
nextOdom = transformNextQr(t,R,qrNextHidden[1])
print("\nPos of 1 in Odom: \n{}".format(nextOdom))

QR pose in odom:
 [(-4.226, 3.176), (-6.003, 3.2173), (-6.708, 0.99), (-5.106, -3.344), (-3.67, -3.178)]

From qr 4 and 5, detect odom position of 1: 

4 in hidden frame: (-3.08, 1.95)
4 in Odom: (-5.106, -3.344)

5 in hidden frame: (-3.08, 0.0)
5 in Odom: (-3.67, -3.178)

Pos of 1 in Odom: 
[[-7.26146894]
 [-0.39199299]
 [ 0.        ]]


In [10]:
print("QR pose in odom:\n",qrOdom)

print("\nFrom qr 1 and 2, detect odom position of 3: ")
print("\n1 in hidden frame: {}".format(qrCurrHidden[0]))
print("1 in Odom: {}".format(qrOdom[3]))
print("\n2 in hidden frame: {}".format(qrCurrHidden[1]))
print("2 in Odom: {}".format(qrOdom[4]))

t,R = kabsch( [qrCurrHidden[3],qrCurrHidden[4]], [qrOdom[3],qrOdom[4]])
nextOdom = transformNextQr(t,R,qrNextHidden[1])
print("\nPos of 3 in Odom: \n{}".format(nextOdom))

QR pose in odom:
 [(-4.675, 2.946), (-6.239, 2.884), (-6.708, 0.99), (-5.106, -3.344), (-3.67, -3.178)]

From qr 1 and 2, detect odom position of 3: 

1 in hidden frame: (3.03, 1.15)
1 in Odom: (-5.106, -3.344)

2 in hidden frame: (2.67, 3.23)
2 in Odom: (-3.67, -3.178)

Pos of 3 in Odom: 
[[-7.26146894]
 [-0.39199299]
 [ 0.        ]]


In [11]:
# LAYOUT 2
qrCurrHidden2 = [(3.03,1.15),(2.67,3.23),(0.1,3.5),(-3.08,1.95),(-3.08,0.0)]
qrNextHidden2 = [(2.7,3.27),(0.1,3.5),(-3.1,2.0),(-3.1,0.0),(3.0,1.2)]

qrOdom2 = [(-4.675,2.946),(-6.239,2.884),(-6.708,0.990),(-5.106,-3.344),(-3.670,-3.178)]
print("QR pose in odom:\n",qrOdom2)

print("\nFrom qr 4 and 5, detect odom position of 1: ")
print("\n4 in hidden frame: {}".format(qrCurrHidden2[3]))
print("4 in Odom: {}".format(qrOdom2[3]))
print("\n5 in hidden frame: {}".format(qrCurrHidden2[4]))
print("5 in Odom: {}".format(qrOdom2[4]))

t,R = kabsch( [qrCurrHidden2[3],qrCurrHidden2[4]], [qrOdom2[3],qrOdom2[4]])
nextOdom2 = transformNextQr(t,R,qrNextHidden2[4])
print("\nPos of 1 in Odom: \n{}".format(nextOdom2))

QR pose in odom:
 [(-4.675, 2.946), (-6.239, 2.884), (-6.708, 0.99), (-5.106, -3.344), (-3.67, -3.178)]

From qr 4 and 5, detect odom position of 1: 

4 in hidden frame: (-3.08, 1.95)
4 in Odom: (-5.106, -3.344)

5 in hidden frame: (-3.08, 0.0)
5 in Odom: (-3.67, -3.178)

Pos of 1 in Odom: 
[[-5.30970326]
 [ 2.75294115]
 [ 0.        ]]
